trigger:
- main

pool:
  name: Milan_agent

stages:
- stage: TerraformDeployment
  displayName: 'Terraform Deployment Stage'
  jobs:
  - job: TerraformJob
    displayName: 'Run Terraform'
    steps:
    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        backendAzureRmResourceGroupName: 'milan-rg'
        backendAzureRmStorageAccountName: 'milanstg'
        backendAzureRmContainerName: 'milancont'
        backendAzureRmKey: 'terraform.tfstate'
        backendServiceArm: 'Azure subscription 1(799b8ac2-95c2-49ae-bf18-9a3bf3936b19)'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        environmentServiceNameAzureRM: 'Azure subscription 1(799b8ac2-95c2-49ae-bf18-9a3bf3936b19)'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Apply'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        environmentServiceNameAzureRM: 'Azure subscription 1(799b8ac2-95c2-49ae-bf18-9a3bf3936b19)'
        allowTelemetryCollection: false
